Repository lingua-games/play-lingua, pull requests merged in 2020-10, with the labels that each got.

#8 First front end design
  README.md
  client/package-lock.json
  client/package.json
  client/src/app/app-routing.module.ts
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/main/game/falling-stars/falling-stars.component.html
  client/src/app/main/game/falling-stars/falling-stars.component.scss
  client/src/app/main/game/falling-stars/falling-stars.component.spec.ts
  client/src/app/main/game/falling-stars/falling-stars.component.ts
  client/src/app/main/main-routing.module.ts
  client/src/app/main/main.component.html
  client/src/app/main/main.component.scss
  client/src/app/main/main.component.spec.ts
  client/src/app/main/main.component.ts
  client/src/app/main/main.module.ts
  client/src/app/service/games.service.spec.ts
  client/src/app/service/games.service.ts
  client/src/styles.scss
  client/tslint.json
Labels: Front-end, Test

#14 Design architecture of super mario game
  client/src/app/main/game/falling-stars/falling-stars.component.html
  client/src/app/main/game/super-mario/super-mario.component.html
  client/src/app/main/game/super-mario/super-mario.component.scss
  client/src/app/main/game/super-mario/super-mario.component.spec.ts
  client/src/app/main/game/super-mario/super-mario.component.ts
  client/src/app/main/main-routing.module.ts
  client/src/app/main/main.component.html
  client/src/app/main/main.module.ts
  client/src/app/models/Mario.ts
  client/src/app/models/element-style.model.ts
Labels: Front-end, New feature

#20 Super mario improvements
  client/angular.json
  client/package-lock.json
  client/package.json
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/core/models/Mario.model.ts
  client/src/app/core/models/element-style.model.ts
  client/src/app/core/models/falling-stars-word.interface.ts
  client/src/app/core/models/score.interface.ts
  client/src/app/core/service/games.service.spec.ts
  client/src/app/core/service/games.service.ts
  client/src/app/main/game/super-mario/super-mario.component.ts
  client/src/app/modules/common/material/material.module.ts
  client/src/app/modules/main/dashboard/dashboard.component.html
  client/src/app/modules/main/dashboard/dashboard.component.scss
  client/src/app/modules/main/dashboard/dashboard.component.spec.ts
  client/src/app/modules/main/dashboard/dashboard.component.ts
  client/src/app/modules/main/game/falling-stars/falling-stars.component.html
  client/src/app/modules/main/game/falling-stars/falling-stars.component.scss
  client/src/app/modules/main/game/falling-stars/falling-stars.component.spec.ts
  client/src/app/modules/main/game/falling-stars/falling-stars.component.ts
  client/src/app/modules/main/game/super-mario/super-mario.component.html
  client/src/app/modules/main/game/super-mario/super-mario.component.scss
  client/src/app/modules/main/game/super-mario/super-mario.component.spec.ts
  client/src/app/modules/main/game/super-mario/super-mario.component.ts
  client/src/app/modules/main/main-routing.module.ts
  client/src/app/modules/main/main.component.html
  client/src/app/modules/main/main.component.scss
  client/src/app/modules/main/main.component.spec.ts
  client/src/app/modules/main/main.component.ts
  client/src/app/modules/main/main.module.ts
  client/src/index.html
  client/src/styles.scss
Labels: Front-end, UI-Design

#21 Done with designing Mario enemies
  README.md
  client/src/app/core/models/element-style.model.ts
  client/src/app/core/models/mario-enemy.model.ts
  client/src/app/modules/main/game/super-mario/super-mario.component.html
  client/src/app/modules/main/game/super-mario/super-mario.component.scss
  client/src/app/modules/main/game/super-mario/super-mario.component.ts
Labels: Front-end, UI-Design

#30 changes in main files for adding the welcome page
  client/angular.json
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/modules/main/main.module.ts
  client/src/app/modules/welcome/welcome-routing.module.ts
  client/src/app/modules/welcome/welcome.component.html
  client/src/app/modules/welcome/welcome.component.scss
  client/src/app/modules/welcome/welcome.component.spec.ts
  client/src/app/modules/welcome/welcome.component.ts
  client/src/app/modules/welcome/welcome.module.ts
  client/src/assets/images/background/welcome-background.png
  client/src/styles.scss
Labels: Front-end, New feature, UI-Design

#33 Super mario improvement
  client/package.json
  client/src/app/app.component.spec.ts
  client/src/app/core/models/Mario.model.ts
  client/src/app/core/models/element-style.model.ts
  client/src/app/modules/main/game/super-mario/super-mario.component.html
  client/src/app/modules/main/game/super-mario/super-mario.component.ts
  client/src/app/modules/main/main.component.spec.ts
Labels: Front-end, Improvement
